// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJhAgY4fclO3AxT-gMYW_tqHWYrKJ_omc',
    appId: '1:335212168996:web:3a67883df605185df1d5b1',
    messagingSenderId: '335212168996',
    projectId: 'fluttercontacts-70d58',
    authDomain: 'fluttercontacts-70d58.firebaseapp.com',
    storageBucket: 'fluttercontacts-70d58.appspot.com',
    measurementId: 'G-XGB442HYKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKv20INpjn6zNvhdTBtJLVihMzM8aUQKM',
    appId: '1:335212168996:android:5afe1b42b0360c1bf1d5b1',
    messagingSenderId: '335212168996',
    projectId: 'fluttercontacts-70d58',
    storageBucket: 'fluttercontacts-70d58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAbnhSJQti4zemVA8XwsbgDucWo3IjSWY',
    appId: '1:335212168996:ios:9b91eceeb5b2fc89f1d5b1',
    messagingSenderId: '335212168996',
    projectId: 'fluttercontacts-70d58',
    storageBucket: 'fluttercontacts-70d58.appspot.com',
    iosBundleId: 'com.example.fluttercontact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAbnhSJQti4zemVA8XwsbgDucWo3IjSWY',
    appId: '1:335212168996:ios:9b91eceeb5b2fc89f1d5b1',
    messagingSenderId: '335212168996',
    projectId: 'fluttercontacts-70d58',
    storageBucket: 'fluttercontacts-70d58.appspot.com',
    iosBundleId: 'com.example.fluttercontact',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJhAgY4fclO3AxT-gMYW_tqHWYrKJ_omc',
    appId: '1:335212168996:web:58a44b4ad7b90146f1d5b1',
    messagingSenderId: '335212168996',
    projectId: 'fluttercontacts-70d58',
    authDomain: 'fluttercontacts-70d58.firebaseapp.com',
    storageBucket: 'fluttercontacts-70d58.appspot.com',
    measurementId: 'G-LGJPZYQFBB',
  );
}
